import { AnalyticsEvent, CareerApplication, Lead, Site, SiteSetting } from "../../models/index.js";

const SITE = "markgenexes";
const eventNames = new Set(["page_view", "lead_submission", "service_enquiry", "consultation_booking", "job_application"]);
const clean = (value, max = 200) => String(value || "").trim().slice(0, max);
async function site() { return Site.findOne({ subdomain: SITE }); }
function trackingJson(setting) {
  const tracking = setting?.tracking || {};
  return {
    googleAnalyticsId: tracking.googleAnalyticsId || "",
    googleAnalyticsEnabled: Boolean(tracking.googleAnalyticsEnabled),
    facebookPixelId: tracking.facebookPixelId || "",
    facebookPixelEnabled: Boolean(tracking.facebookPixelEnabled),
    firstPartyEnabled: tracking.firstPartyEnabled !== false,
    trackPageViews: tracking.trackPageViews !== false,
    trackConversions: tracking.trackConversions !== false,
  };
}
function validGa(value) { return !value || /^G-[A-Z0-9]{5,20}$/i.test(value); }
function validPixel(value) { return !value || /^\d{5,25}$/.test(value); }

export class TrackingController {
  static async publicConfig(req, res) { try { const currentSite = await site(); if (!currentSite) return res.json({ tracking: trackingJson() }); const setting = await SiteSetting.findOne({ site: currentSite._id }); return res.json({ tracking: trackingJson(setting) }); } catch { return res.json({ tracking: trackingJson() }); } }
  static async adminConfig(req, res) { try { const currentSite = await site(); const setting = currentSite ? await SiteSetting.findOne({ site: currentSite._id }) : null; return res.json({ tracking: trackingJson(setting) }); } catch (e) { return res.status(500).json({ error: "Failed to load tracking settings", details: e.message }); } }
  static async updateConfig(req, res) { try { const currentSite = await site(); if (!currentSite) return res.status(404).json({ error: "Site not found" }); const ga = clean(req.body.googleAnalyticsId, 30).toUpperCase(), pixel = clean(req.body.facebookPixelId, 30); if (!validGa(ga)) return res.status(400).json({ error: "Use a valid GA4 Measurement ID, for example G-XXXXXXXXXX" }); if (!validPixel(pixel)) return res.status(400).json({ error: "Meta Pixel ID must contain numbers only" }); const tracking = { googleAnalyticsId: ga, googleAnalyticsEnabled: Boolean(req.body.googleAnalyticsEnabled && ga), facebookPixelId: pixel, facebookPixelEnabled: Boolean(req.body.facebookPixelEnabled && pixel), firstPartyEnabled: req.body.firstPartyEnabled !== false, trackPageViews: req.body.trackPageViews !== false, trackConversions: req.body.trackConversions !== false }; const fields = Object.fromEntries(Object.entries(tracking).map(([key, value]) => [`tracking.${key}`, value])); const setting = await SiteSetting.findOneAndUpdate({ site: currentSite._id }, { $set: fields }, { new: true, upsert: true }); return res.json({ message: "Tracking settings saved", tracking: trackingJson(setting) }); } catch (e) { return res.status(400).json({ error: "Failed to save tracking settings", details: e.message }); } }
  static async collect(req, res) { try { const currentSite = await site(); if (!currentSite) return res.status(204).end(); const setting = await SiteSetting.findOne({ site: currentSite._id }); if (setting?.tracking?.firstPartyEnabled === false) return res.status(204).end(); const name = clean(req.body.eventName, 60); if (!eventNames.has(name)) return res.status(400).json({ error: "Unsupported event" }); const utm = req.body.utm || {}; await AnalyticsEvent.create({ site: currentSite._id, eventType: name === "page_view" ? "page_view" : "conversion", eventName: name, eventProperties: { pagePath: clean(req.body.pagePath, 500), jobId: clean(req.body.jobId, 50), jobTitle: clean(req.body.jobTitle, 150) }, sessionId: clean(req.body.sessionId, 100), anonymousId: clean(req.body.anonymousId, 100), ipAddress: req.ip, userAgent: clean(req.get("user-agent"), 500), referrer: clean(req.body.referrer, 500), language: clean(req.body.language, 20), utm: { source: clean(utm.source || utm.utm_source), medium: clean(utm.medium || utm.utm_medium), campaign: clean(utm.campaign || utm.utm_campaign), term: clean(utm.term || utm.utm_term), content: clean(utm.content || utm.utm_content) }, gclid: clean(req.body.gclid), fbclid: clean(req.body.fbclid), timestamp: new Date() }); return res.status(204).end(); } catch { return res.status(204).end(); } }
  static async report(req, res) { try { const currentSite = await site(); if (!currentSite) return res.json({ summary: {}, campaigns: [], events: [] }); const days = Math.min(365, Math.max(1, Number(req.query.days || 30))), since = new Date(Date.now() - days * 86400000); const [events, leadCount, applicationCount] = await Promise.all([AnalyticsEvent.find({ site: currentSite._id, timestamp: { $gte: since } }).sort({ timestamp: -1 }).limit(1000).lean(), Lead.countDocuments({ site: currentSite._id, createdAt: { $gte: since } }), CareerApplication.countDocuments({ appliedAt: { $gte: since } })]); const campaignMap = new Map(); for (const event of events) { const key = [event.utm?.source || "direct", event.utm?.medium || "none", event.utm?.campaign || "(not set)"].join("|"); const row = campaignMap.get(key) || { source: event.utm?.source || "direct", medium: event.utm?.medium || "none", campaign: event.utm?.campaign || "(not set)", pageViews: 0, conversions: 0 }; event.eventType === "page_view" ? row.pageViews++ : row.conversions++; campaignMap.set(key, row); } const pageViews = events.filter((x) => x.eventType === "page_view").length, conversions = events.filter((x) => x.eventType === "conversion").length; return res.json({ summary: { pageViews, conversions, leads: leadCount, applications: applicationCount, conversionRate: pageViews ? Number(((conversions / pageViews) * 100).toFixed(1)) : 0 }, campaigns: [...campaignMap.values()].sort((a,b) => b.conversions-a.conversions || b.pageViews-a.pageViews).slice(0,50), events: events.slice(0,25).map((x) => ({ id: String(x._id), name: x.eventName, pagePath: x.eventProperties?.pagePath || "", source: x.utm?.source || "direct", campaign: x.utm?.campaign || "", timestamp: x.timestamp })) }); } catch (e) { return res.status(500).json({ error: "Failed to load tracking report", details: e.message }); } }
}
