import { useEffect,useState } from 'react'
import { ChevronDown,ChevronUp,ImageUp,Loader2,Pencil,Plus,Trash2 } from 'lucide-react'
import { createCaseStudy,deleteCaseStudy,getAdminCaseStudies,updateCaseStudy,uploadCaseStudyImage } from '../lib/api'
import { Badge } from './ui/badge'
import { Button } from './ui/button'
import { Dialog } from './ui/dialog'
import { Field,Input,Select,Textarea } from './ui/field'

const blank={title:'',clientName:'',industry:'',bannerImage:'',metric1Value:'',metric1Label:'',metric2Value:'',metric2Label:'',metric3Value:'',metric3Label:'',services:'',displayOrder:0,status:'draft'}
const form=(item)=>({...item,metric1Value:item.metrics?.[0]?.value||'',metric1Label:item.metrics?.[0]?.label||'',metric2Value:item.metrics?.[1]?.value||'',metric2Label:item.metrics?.[1]?.label||'',metric3Value:item.metrics?.[2]?.value||'',metric3Label:item.metrics?.[2]?.label||'',services:(item.services||[]).join('\n')})
const payload=(item)=>({...item,metrics:[1,2,3].map((i)=>({value:item[`metric${i}Value`],label:item[`metric${i}Label`]})),services:String(item.services).split('\n').map((x)=>x.trim()).filter(Boolean)})
export function CaseStudyManager(){const[items,setItems]=useState([]),[editing,setEditing]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[feedback,setFeedback]=useState('');useEffect(()=>{let active=true;getAdminCaseStudies().then((x)=>active&&setItems(x)).catch((e)=>active&&setFeedback(e.message)).finally(()=>active&&setLoading(false));return()=>{active=false}},[]);const change=(key,value)=>setEditing((x)=>({...x,[key]:value}));const ordered=(x)=>[...x].sort((a,b)=>a.displayOrder-b.displayOrder)
async function save(e){e.preventDefault();setBusy(true);setFeedback('');try{const saved=editing.id?await updateCaseStudy(editing.id,payload(editing)):await createCaseStudy(payload(editing));setItems((x)=>ordered([...x.filter((i)=>i.id!==saved.id),saved]));setEditing(null);setFeedback('Case study saved successfully.')}catch(error){setFeedback(error.message)}finally{setBusy(false)}}async function patch(item,values){try{const saved=await updateCaseStudy(item.id,{...item,...values});setItems((x)=>ordered(x.map((i)=>i.id===saved.id?saved:i)));return saved}catch(e){setFeedback(e.message)}}async function move(item,d){const index=items.findIndex((x)=>x.id===item.id),other=items[index+d];if(other)await Promise.all([patch(item,{displayOrder:other.displayOrder}),patch(other,{displayOrder:item.displayOrder})])}async function remove(item){if(!window.confirm(`Delete “${item.title}”?`))return;try{await deleteCaseStudy(item.id);setItems((x)=>x.filter((i)=>i.id!==item.id))}catch(e){setFeedback(e.message)}}async function upload(file){if(!file)return;setUploading(true);try{const image=await uploadCaseStudyImage(file);change('bannerImage',image.url)}catch(e){setFeedback(e.message)}finally{setUploading(false)}}
return <section className="surface-card min-w-0 rounded-lg p-4 sm:p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-bold text-ink">Case Studies Management</h2><p className="mt-1 text-sm text-muted-foreground">Manage the exact content displayed on each public case-study card.</p></div><Button onClick={()=>setEditing({...blank,displayOrder:items.length})}><Plus className="size-4"/>Add Case Study</Button></div>{feedback?<p className="mt-3 rounded-md border border-border bg-muted/50 px-3 py-2 text-sm">{feedback}</p>:null}{loading?<div className="grid place-items-center py-10"><Loader2 className="size-6 animate-spin text-primary"/></div>:<div className="mt-4 grid gap-3">{items.map((item,index)=><article key={item.id} className="flex flex-col gap-4 rounded-lg border border-border bg-white p-4 md:flex-row md:items-center"><img src={item.bannerImage} alt="" className="h-24 w-full rounded-md object-cover md:w-36"/><div className="min-w-0 flex-1"><div className="flex gap-2"><Badge>{item.status}</Badge><Badge>{item.industry}</Badge></div><h3 className="mt-2 font-bold text-ink">{item.title}</h3><p className="text-xs text-muted-foreground">{item.clientName}</p></div><div className="flex flex-wrap gap-2"><Button size="icon" variant="outline" disabled={!index} onClick={()=>move(item,-1)}><ChevronUp className="size-4"/></Button><Button size="icon" variant="outline" disabled={index===items.length-1} onClick={()=>move(item,1)}><ChevronDown className="size-4"/></Button><Button size="sm" onClick={()=>setEditing(form(item))}><Pencil className="size-4"/>Edit</Button><Button size="sm" variant="outline" onClick={()=>patch(item,{status:item.status==='published'?'draft':'published'})}>{item.status==='published'?'Unpublish':'Publish'}</Button><Button size="icon" variant="ghost" className="text-red-600" onClick={()=>remove(item)}><Trash2 className="size-4"/></Button></div></article>)}</div>}
<Dialog open={Boolean(editing)} onOpenChange={(open)=>!open&&setEditing(null)} title={editing?.id?'Edit Case Study':'Add Case Study'} description="These fields map directly to the public card." className="sm:max-w-4xl">{editing?<form onSubmit={save} className="grid gap-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="Case Study Title *"><Input required value={editing.title} onChange={(e)=>change('title',e.target.value)}/></Field><Field label="Client / Brand Name *"><Input required value={editing.clientName} onChange={(e)=>change('clientName',e.target.value)}/></Field><Field label="Industry *"><Input required value={editing.industry} onChange={(e)=>change('industry',e.target.value)}/></Field><Field label="Publish Status"><Select value={editing.status} onChange={(e)=>change('status',e.target.value)}><option value="draft">Draft</option><option value="published">Published</option></Select></Field></div><Field label="Case Study Image *"><div className="rounded-lg border border-dashed border-border p-3">{editing.bannerImage?<img src={editing.bannerImage} alt="Preview" className="mb-3 aspect-[16/9] w-full rounded-md object-cover"/>:null}<label className="inline-flex cursor-pointer items-center gap-2 font-bold text-primary"><ImageUp className="size-4"/>{uploading?'Uploading…':'Upload image'}<input className="sr-only" type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={(e)=>upload(e.target.files?.[0])}/></label></div></Field><div className="grid gap-4 sm:grid-cols-3">{[1,2,3].map((i)=><div key={i} className="grid gap-3 rounded-lg border border-border p-3"><p className="font-bold text-ink">Metric {i}</p><Field label="Value *"><Input required placeholder="2.5×" value={editing[`metric${i}Value`]} onChange={(e)=>change(`metric${i}Value`,e.target.value)}/></Field><Field label="Label *"><Input required placeholder="Inquiries" value={editing[`metric${i}Label`]} onChange={(e)=>change(`metric${i}Label`,e.target.value)}/></Field></div>)}</div><Field label="Service Tags (one per line)"><Textarea placeholder={'SEO\nContent\nWeb'} value={editing.services} onChange={(e)=>change('services',e.target.value)}/></Field><Button disabled={busy||uploading||!editing.bannerImage}>{busy?<Loader2 className="size-4 animate-spin"/>:null}{busy?'Saving…':'Save Case Study'}</Button></form>:null}</Dialog></section>}
