import { useEffect, useState } from 'react'
import { CheckCircle2, Loader2, RefreshCw, Save } from 'lucide-react'
import { getTrackingReport, getTrackingSettings, saveTrackingSettings } from '../lib/api'
import { Badge } from './ui/badge'
import { Button } from './ui/button'
import { Field, Input, Select } from './ui/field'

const defaults = { googleAnalyticsId: '', googleAnalyticsEnabled: false, facebookPixelId: '', facebookPixelEnabled: false, firstPartyEnabled: true, trackPageViews: true, trackConversions: true }
const Toggle = ({ label, description, checked, onChange, disabled }) => <label className="flex cursor-pointer items-start justify-between gap-4 rounded-md border border-border bg-white p-3"><span><b className="block text-sm text-ink">{label}</b><span className="mt-1 block text-xs leading-5 text-muted-foreground">{description}</span></span><input type="checkbox" className="mt-1 size-4 accent-[var(--color-primary)]" checked={checked} disabled={disabled} onChange={(e) => onChange(e.target.checked)} /></label>

export function TrackingManager() {
  const [settings, setSettings] = useState(defaults), [report, setReport] = useState(null), [days, setDays] = useState('30')
  const [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [feedback, setFeedback] = useState('')
  const load = async (range = days) => { setLoading(true); setFeedback(''); try { const [config, data] = await Promise.all([getTrackingSettings(), getTrackingReport(range)]); setSettings(config); setReport(data) } catch (e) { setFeedback(e.message) } finally { setLoading(false) } }
  useEffect(() => { let active = true; Promise.all([getTrackingSettings(), getTrackingReport(30)]).then(([config, data]) => { if (active) { setSettings(config); setReport(data) } }).catch((e) => { if (active) setFeedback(e.message) }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [])
  const change = (name, value) => setSettings((current) => ({ ...current, [name]: value }))
  async function save(event) { event.preventDefault(); setSaving(true); setFeedback(''); try { setSettings(await saveTrackingSettings(settings)); setFeedback('Tracking settings saved. They will apply to new page loads.') } catch (e) { setFeedback(e.message) } finally { setSaving(false) } }
  return <section className="surface-card min-w-0 rounded-lg p-4 sm:p-5 lg:col-span-2">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="text-xl font-bold text-ink">Tracking & Attribution</h2><p className="mt-1 text-sm text-muted-foreground">Configure analytics providers and review first-party conversion data.</p></div><div className="flex gap-2"><Select className="w-28" value={days} onChange={(e) => { setDays(e.target.value); load(e.target.value) }} aria-label="Report range"><option value="7">7 days</option><option value="30">30 days</option><option value="90">90 days</option><option value="365">1 year</option></Select><Button size="icon" variant="outline" onClick={() => load()} aria-label="Refresh report"><RefreshCw className="size-4" /></Button></div></div>
    {feedback ? <p className="mt-4 rounded-md border border-border bg-muted/50 px-3 py-2 text-sm" role="status">{feedback}</p> : null}
    {loading ? <div className="grid place-items-center py-12"><Loader2 className="size-6 animate-spin text-primary" /></div> : <>
      <div className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-5">{[['Page views',report?.summary?.pageViews || 0],['Conversions',report?.summary?.conversions || 0],['Conversion rate',`${report?.summary?.conversionRate || 0}%`],['Leads',report?.summary?.leads || 0],['Applications',report?.summary?.applications || 0]].map(([label,value]) => <div key={label} className="rounded-md border border-border bg-white p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-black text-ink">{value}</p></div>)}</div>
      <form onSubmit={save} className="mt-5 grid gap-4"><div className="grid gap-4 lg:grid-cols-2"><div className="rounded-lg border border-border p-4"><div className="flex items-center justify-between"><h3 className="font-bold text-ink">Google Analytics 4</h3><Badge>{settings.googleAnalyticsEnabled ? 'Active' : 'Inactive'}</Badge></div><Field className="mt-4" label="Measurement ID"><Input placeholder="G-XXXXXXXXXX" value={settings.googleAnalyticsId} onChange={(e) => change('googleAnalyticsId', e.target.value)} /></Field><div className="mt-3"><Toggle label="Enable GA4" description="Send configured page views and conversion events to Google Analytics." checked={settings.googleAnalyticsEnabled} disabled={!settings.googleAnalyticsId} onChange={(v) => change('googleAnalyticsEnabled', v)} /></div></div><div className="rounded-lg border border-border p-4"><div className="flex items-center justify-between"><h3 className="font-bold text-ink">Meta Pixel</h3><Badge>{settings.facebookPixelEnabled ? 'Active' : 'Inactive'}</Badge></div><Field className="mt-4" label="Pixel ID"><Input inputMode="numeric" placeholder="123456789012345" value={settings.facebookPixelId} onChange={(e) => change('facebookPixelId', e.target.value)} /></Field><div className="mt-3"><Toggle label="Enable Meta Pixel" description="Send page views and lead conversions to Meta." checked={settings.facebookPixelEnabled} disabled={!settings.facebookPixelId} onChange={(v) => change('facebookPixelEnabled', v)} /></div></div></div>
        <div className="grid gap-3 sm:grid-cols-3"><Toggle label="First-party tracking" description="Store attribution events in this database." checked={settings.firstPartyEnabled} onChange={(v) => change('firstPartyEnabled', v)} /><Toggle label="Page views" description="Record visits and campaign landing pages." checked={settings.trackPageViews} onChange={(v) => change('trackPageViews', v)} /><Toggle label="Conversions" description="Record successful forms and applications." checked={settings.trackConversions} onChange={(v) => change('trackConversions', v)} /></div><Button className="w-full sm:w-auto sm:justify-self-end" disabled={saving}>{saving ? <Loader2 className="size-4 animate-spin" /> : <Save className="size-4" />}{saving ? 'Saving…' : 'Save Tracking Settings'}</Button>
      </form>
      <div className="mt-6"><h3 className="font-bold text-ink">UTM campaign performance</h3><div className="mt-3 overflow-x-auto rounded-lg border border-border"><table className="w-full min-w-[600px] text-left text-sm"><thead className="bg-muted"><tr>{['Source','Medium','Campaign','Page views','Conversions'].map((x) => <th key={x} className="px-3 py-2 font-bold">{x}</th>)}</tr></thead><tbody>{report?.campaigns?.map((row) => <tr key={`${row.source}-${row.medium}-${row.campaign}`} className="border-t border-border"><td className="px-3 py-2">{row.source}</td><td className="px-3 py-2">{row.medium}</td><td className="px-3 py-2">{row.campaign}</td><td className="px-3 py-2">{row.pageViews}</td><td className="px-3 py-2 font-bold">{row.conversions}</td></tr>)}</tbody></table>{!report?.campaigns?.length ? <p className="p-5 text-center text-sm text-muted-foreground">No tracking data yet. Use a URL with UTM parameters and submit a form to test attribution.</p> : null}</div></div>
      <div className="mt-6"><h3 className="font-bold text-ink">Recent events</h3><div className="mt-3 grid gap-2">{report?.events?.map((event) => <div key={event.id} className="flex flex-col gap-1 rounded-md border border-border bg-white p-3 text-sm sm:flex-row sm:items-center sm:justify-between"><span className="flex items-center gap-2"><CheckCircle2 className="size-4 text-primary" /><b>{event.name}</b><span className="text-muted-foreground">{event.pagePath}</span></span><span className="text-xs text-muted-foreground">{event.source}{event.campaign ? ` / ${event.campaign}` : ''} · {new Date(event.timestamp).toLocaleString()}</span></div>)}</div></div>
    </>}
  </section>
}
