import mongoose from "mongoose";
import { CaseStudy, Site, StoredImage } from "../../models/index.js";
import { CloudImageUtil } from "../../utils/media/CloudImageUtil.js";

const SITE = "markgenexes";
const slugify = (value) => String(value || "").toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
const services = (value) => (Array.isArray(value) ? value : String(value || "").split("\n")).map(String).map((x) => x.trim()).filter(Boolean).slice(0, 12);
const metrics = (value) => { const items = typeof value === "string" ? JSON.parse(value || "[]") : value; if (!Array.isArray(items) || items.length !== 3) throw new Error("Exactly three metrics are required"); return items.map((item) => ({ value: String(item.value || "").trim(), label: String(item.label || item.metric || "").trim() })).map((item) => { if (!item.value || !item.label) throw new Error("Each metric requires a value and label"); return item; }); };
async function getSite() { return Site.findOne({ subdomain: SITE }); }
function json(item) { return { id: String(item._id), title: item.title, slug: item.slug, clientName: item.clientName || item.client?.name || "", industry: item.industry || item.client?.industry || "", bannerImage: item.bannerImage || "", metrics: item.metrics?.length ? item.metrics : (item.results || []).slice(0, 3).map((x) => ({ value: x.value, label: x.metric })), services: item.services?.length ? item.services : item.servicesUsed || [], displayOrder: item.displayOrder || 0, status: item.status, publishedAt: item.publishedAt }; }
function payload(body, current = {}) { const title = String(body.title ?? current.title ?? "").trim(), clientName = String(body.clientName ?? current.clientName ?? current.client?.name ?? "").trim(), industry = String(body.industry ?? current.industry ?? current.client?.industry ?? "").trim(), bannerImage = String(body.bannerImage ?? current.bannerImage ?? "").trim(); if (!title || !clientName || !industry || !bannerImage) throw new Error("Title, client name, industry, and image are required"); return { title, slug: slugify(title), clientName, industry, bannerImage, metrics: metrics(body.metrics ?? current.metrics ?? current.results ?? []), services: services(body.services ?? current.services ?? current.servicesUsed), displayOrder: Math.max(0, Number(body.displayOrder ?? current.displayOrder ?? 0)), status: ["draft", "published"].includes(body.status) ? body.status : current.status || "draft" }; }
const obsolete = { summary:1, fullDescription:1, client:1, challenge:1, solution:1, process:1, servicesUsed:1, results:1, testimonial:1, testimonialAuthor:1, additionalImages:1, ctaText:1, ctaLink:1, seoTitle:1, metaDescription:1, featured:1, images:1, service:1 };
export class CaseStudyController {
  static async publicList(req,res){try{const site=await getSite();if(!site)return res.json({caseStudies:[]});const items=await CaseStudy.find({site:site._id,status:"published"}).sort({displayOrder:1,publishedAt:-1});return res.json({caseStudies:items.map(json)})}catch(e){return res.status(500).json({error:"Failed to load case studies",details:e.message})}}
  static async adminList(req,res){try{const site=await getSite();if(!site)return res.json({caseStudies:[]});const items=await CaseStudy.find({site:site._id}).sort({displayOrder:1,createdAt:-1});return res.json({caseStudies:items.map(json)})}catch(e){return res.status(500).json({error:"Failed to load case studies",details:e.message})}}
  static async create(req,res){try{const site=await getSite();if(!site)return res.status(404).json({error:"Site not found"});const data=payload(req.body);if(await CaseStudy.exists({site:site._id,slug:data.slug}))return res.status(409).json({error:"A case study with this title already exists"});const item=await CaseStudy.create({site:site._id,...data,...(data.status==="published"?{publishedAt:new Date()}:{})});return res.status(201).json({caseStudy:json(item)})}catch(e){return res.status(400).json({error:"Failed to create case study",details:e.message})}}
  static async update(req,res){try{if(!mongoose.Types.ObjectId.isValid(req.params.id))return res.status(400).json({error:"Invalid case study ID"});const item=await CaseStudy.findById(req.params.id);if(!item)return res.status(404).json({error:"Case study not found"});const data=payload(req.body,item.toObject());if(await CaseStudy.exists({site:item.site,slug:data.slug,_id:{$ne:item._id}}))return res.status(409).json({error:"A case study with this title already exists"});await CaseStudy.updateOne({_id:item._id},{$set:{...data,...(data.status==="published"&&!item.publishedAt?{publishedAt:new Date()}:{})},$unset:obsolete});const saved=await CaseStudy.findById(item._id);return res.json({caseStudy:json(saved)})}catch(e){return res.status(400).json({error:"Failed to update case study",details:e.message})}}
  static async remove(req,res){try{const item=await CaseStudy.findByIdAndDelete(req.params.id);if(!item)return res.status(404).json({error:"Case study not found"});return res.json({message:"Case study deleted"})}catch(e){return res.status(400).json({error:"Failed to delete case study",details:e.message})}}
  static async upload(req,res){try{if(!req.file)return res.status(400).json({error:"Choose an image to upload"});if(CloudImageUtil.configured()){const image=await CloudImageUtil.upload(req.file);return res.status(201).json({image,storage:"cloudinary"})}const site=await getSite();if(!site)return res.status(404).json({error:"Site not found"});const stored=await StoredImage.create({site:site._id,fileName:req.file.originalname,mimeType:req.file.mimetype,size:req.file.size,data:req.file.buffer,uploadedBy:req.user.id});const url=`/api/v1/public/case-study-images/${stored._id}`;return res.status(201).json({image:{url},storage:"database"})}catch(e){return res.status(500).json({error:"Image upload failed",details:e.message})}}
  static async image(req,res){try{if(!mongoose.Types.ObjectId.isValid(req.params.id))return res.status(404).end();const image=await StoredImage.findById(req.params.id).select("+data");if(!image)return res.status(404).end();res.setHeader("Content-Type",image.mimeType);res.setHeader("Content-Length",image.size);res.setHeader("Cache-Control","public, max-age=31536000, immutable");res.setHeader("X-Content-Type-Options","nosniff");return res.send(image.data)}catch{return res.status(404).end()}}
}
